-- ============================================================
-- seed.sql — default revenue categories (Konshisha IGR)
-- Seeds the 56 canonical revenue heads if they do not already exist.
-- Apply after migrations via: supabase db seed (or psql)
-- ============================================================

insert into categories (name, default_amount, sort_order) values
  ('Market Stall Fee', null, 1),
  ('Tenement Rate', null, 2),
  ('Billboard', null, 3),
  ('Meat Inspection Fee', null, 4),
  ('Certificate of Occupancy', null, 5),
  ('Vehicle Registration', null, 6),
  ('Liquor License', null, 7),
  ('Signage / Advertisement', null, 8),
  ('Marriage Registration', null, 9),
  ('Bicycle / Tricycle Permit', null, 10),
  ('Hawkers Levy', null, 11),
  ('Street Trading Levy', null, 12),
  ('Slaughter Slab Fee', null, 13),
  ('Abattoir Fee', null, 14),
  ('Environmental Sanitation Levy', null, 15),
  ('Refuse Collection Fee', null, 16),
  ('Borehole / Water', null, 17),
  ('Motor Park Levy', null, 18),
  ('Loading / Offloading Fee', null, 19),
  ('Ticket / Parking Fee', null, 20),
  ('Building Permit', null, 21),
  ('Business Premises Registration', null, 22),
  ('Petty Trading Permit', null, 23),
  ('Liquor / Palm Wine Tapping', null, 24),
  ('Timber / Sawmilling Tax', null, 25),
  ('Television / Radio License', null, 26),
  ('Fire Service Levy', null, 27),
  ('Nightclub / Bar Permit', null, 28),
  ('Hotel / Guesthouse Permit', null, 29),
  ('Restaurant Permit', null, 30),
  ('Film / Video Recording', null, 31),
  ('Commercial Motorcycle (Okada)', null, 32),
  ('Commercial Tricycle (Keke)', null, 33),
  ('Commercial Buses', null, 34),
  ('Taxi / Cab Permit', null, 35),
  ('Truck / Lorry Levy', null, 36),
  ('Tractor / Farm Implement', null, 37),
  ('Canoe / Boat (Jetty) Fee', null, 38),
  ('Pond / Fishery Fees', null, 39),
  ('Hunting Permit', null, 40),
  ('Facility / Hall Hiring', null, 41),
  ('Game / Recreation Fee', null, 42),
  ('Development Levy', null, 43),
  ('Community Development Levy', null, 44),
  ('Education Levy', null, 45),
  ('Health / Sanitation Levy', null, 46),
  ('Public Toilet Fee', null, 47),
  ('Land / Plot Fees', null, 48),
  ('Bridging / Culvert', null, 49),
  ('Grazing / Cattle Route', null, 50),
  ('Neighbourhood Watch', null, 51),
  ('Security Levy', null, 52),
  ('Burial / Cemetry Fee', null, 53),
  ('Market Wharfage', null, 54),
  ('Customary Court Fees', null, 55),
  ('Other Levies', null, 56)
on conflict (name) do nothing;
