const List<String> defaultRevenueCategories = [
  'Abbatoir License Fee',
  'Advertising Board Fee',
  'Akpu',
  'Bank',
  'Billboard',
  'Building Plan Approval',
  'Business Premises License',
  'Cattle Pass Fee',
  'Certificate of Occupancy',
  'Checkpoint',
  'Chicken/Fowls',
  'Departmental Receipt',
  'Development Levy',
  'Dogs',
  'Event Permit Fee',
  'Fashion',
  'Fire Service Charge',
  'Filling Station',
  'Fish Section',
  'Gate Pass',
  'Garri Section',
  'Goat/Sheep',
  'Hawkers/Traders Permit',
  'Hospital',
  'Liquor License',
  'Market Stall Fee',
  'Meat Inspection Fee',
  'Main Market',
  'Main Park',
  'Market Committee',
  'Market Levy',
  'Motor Park Booking',
  'Noise Permit Fee',
  'Operational Permit',
  'Park and Ride Fee',
  'Poultry License Fee',
  'Provision',
  'Radio/TV License',
  'Road Construction Levy',
  'Shop & Store',
  'Signage',
  'Signage Ginger',
  'Signage Rice',
  'Signage G-Nut',
  'Signage Garri',
  'Signage Oranges',
  'Stones',
  'Task-Force & Security',
  'Tenement Rate',
  'Tourism Permit Fee',
  'Trade Permit',
  'Vehicle Registration',
  'Way In',
  'Way Out',
  'Welfare',
  'Yam Section',
];
